sea_twi_base_homepage:
    pattern:  /
    defaults: { _controller: SeaTwiBaseBundle:Default:index }

SeaTwiBaseBundle_hashtag:
    resource: "@SeaTwiBaseBundle/Resources/config/routing/hashtag.yml"
    prefix:   /hashtag