parameters:
#    sea_twi_base.example.class: SeaTwi\BaseBundle\Example

services:
#    sea_twi_base.example:
#        class: %sea_twi_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
